spring.application.name=TripZoneProject

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=tripzone
spring.datasource.password=tripzone
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database=oracle
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.id.new_generator_mappings=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
logging.level.org.hibernate=info
# JWT secret key
jwt.secret=sdkfjsiejfhxhciocoianeisofienahffjeisinOEiffndi

# access token expiration time (seconds)
jwt.access-token-expiration=600

# refresh token expiration time (seconds)
jwt.refresh-token-expiration=1209600

# security log
logging.level.org.springframework.security=trace
google.client-id=1022906861001-f2tf54sjdgi64nivbqhtevhsaubdh9js.apps.googleusercontent.com

kakao.client-id=bccf0774846b742756b3ff66558e4269
kakao.client-secret=het4QfDF7xu1JHVHMqIMILgNo7bHPTn8
kakao.redirect-uri=http://localhost:5173/auth/kakao/callback
kakao.local.rest-api-key=${kakao.client-id}

naver.client-id=PqkeWT1NEiTtIXw12Rc4
naver.client-secret=ztRn_vcnCR
naver.redirect-uri=http://localhost:5173/auth/naver/callback

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB

# imagePath
com.kh.upload.path=D:/upload
